//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCPack.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmUserFunction
    {
        public int ID { get; set; }
        public int ConfimID { get; set; }
        public int JobPositionID { get; set; }
        public string JobPositionName { get; set; }
    
        public virtual JobPosition JobPosition { get; set; }
        public virtual ReadConfirmation ReadConfirmation { get; set; }
    }
}
