//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCPack.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GCPackContainer : DbContext
    {
        public GCPackContainer()
            : base("name=GCPackContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSystem> AppSystems { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<JobPosition> JobPositions { get; set; }
        public virtual DbSet<ReadConfirmation> ReadConfirmations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Signature> Signatures { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<JobPositionUser> JobPositionUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<JobPositionDocument> JobPositionDocuments { get; set; }
        public virtual DbSet<UserDocument> UserDocuments { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DivisionDocument> DivisionDocuments { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDocument> ProjectDocuments { get; set; }
        public virtual DbSet<SystemDocument> SystemDocuments { get; set; }
        public virtual DbSet<DocumentState> DocumentStates { get; set; }
        public virtual DbSet<Workplace> Workplaces { get; set; }
        public virtual DbSet<WorkplaceDocument> WorkplaceDocuments { get; set; }
        public virtual DbSet<LogEvent> LogEvents { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    
        public virtual int GetDocuments(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter);
        }
    
        public virtual int GetDocuments1(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments1", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter);
        }
    
        public virtual int GetDocuments2(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments2", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter);
        }
    
        public virtual int GetDocuments3(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments3", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter);
        }
    
        public virtual int GetDocuments4(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments4", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments5(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, string nextReviewDateFrom, string nextReviewDateTo, string effeciencyDateFrom, string effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom != null ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(string));
    
            var nextReviewDateToParameter = nextReviewDateTo != null ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(string));
    
            var effeciencyDateFromParameter = effeciencyDateFrom != null ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(string));
    
            var effeciencyDateToParameter = effeciencyDateTo != null ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments5", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments6(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments6", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments7(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments7", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments8(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments8", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments9(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments9", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter);
        }
    
        public virtual int GetDocuments10(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments10", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter);
        }
    
        public virtual int GetDocuments11(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments11", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter);
        }
    
        public virtual int GetDocuments12(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments12", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter);
        }
    
        public virtual int GetDocuments13(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments13", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter);
        }
    
        public virtual int GetDocuments14(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments14", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter);
        }
    
        public virtual int GetDocuments15(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments15", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter);
        }
    
        public virtual int GetDocuments16(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision, string reviewNecassaryChange)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var reviewNecassaryChangeParameter = reviewNecassaryChange != null ?
                new ObjectParameter("ReviewNecassaryChange", reviewNecassaryChange) :
                new ObjectParameter("ReviewNecassaryChange", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments16", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter, reviewNecassaryChangeParameter);
        }
    
        public virtual int GetDocuments17(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision, string reviewNecassaryChange)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var reviewNecassaryChangeParameter = reviewNecassaryChange != null ?
                new ObjectParameter("ReviewNecassaryChange", reviewNecassaryChange) :
                new ObjectParameter("ReviewNecassaryChange", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments17", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter, reviewNecassaryChangeParameter);
        }
    
        public virtual int GetDocuments18(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision, string reviewNecassaryChange)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var reviewNecassaryChangeParameter = reviewNecassaryChange != null ?
                new ObjectParameter("ReviewNecassaryChange", reviewNecassaryChange) :
                new ObjectParameter("ReviewNecassaryChange", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments18", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter, reviewNecassaryChangeParameter);
        }
    
        public virtual int GetDocuments19(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision, string reviewNecassaryChange, Nullable<int> mainID)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var reviewNecassaryChangeParameter = reviewNecassaryChange != null ?
                new ObjectParameter("ReviewNecassaryChange", reviewNecassaryChange) :
                new ObjectParameter("ReviewNecassaryChange", typeof(string));
    
            var mainIDParameter = mainID.HasValue ?
                new ObjectParameter("MainID", mainID) :
                new ObjectParameter("MainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDocuments19", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter, reviewNecassaryChangeParameter, mainIDParameter);
        }
    
        public virtual ObjectResult<GetDocuments20_Result> GetDocuments20(Nullable<int> forUserID, Nullable<int> documentID, string name, string number, string administrator, string orderBy, Nullable<int> documentTypeID, Nullable<int> page, Nullable<int> itemsPerPage, Nullable<int> projectID, Nullable<int> divisionID, Nullable<int> appSystemID, Nullable<int> workplaceID, Nullable<System.DateTime> nextReviewDateFrom, Nullable<System.DateTime> nextReviewDateTo, Nullable<System.DateTime> effeciencyDateFrom, Nullable<System.DateTime> effeciencyDateTo, string readType, Nullable<int> stateID, string revision, string reviewNecassaryChange, Nullable<int> mainID)
        {
            var forUserIDParameter = forUserID.HasValue ?
                new ObjectParameter("forUserID", forUserID) :
                new ObjectParameter("forUserID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));
    
            var administratorParameter = administrator != null ?
                new ObjectParameter("Administrator", administrator) :
                new ObjectParameter("Administrator", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var divisionIDParameter = divisionID.HasValue ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(int));
    
            var appSystemIDParameter = appSystemID.HasValue ?
                new ObjectParameter("AppSystemID", appSystemID) :
                new ObjectParameter("AppSystemID", typeof(int));
    
            var workplaceIDParameter = workplaceID.HasValue ?
                new ObjectParameter("WorkplaceID", workplaceID) :
                new ObjectParameter("WorkplaceID", typeof(int));
    
            var nextReviewDateFromParameter = nextReviewDateFrom.HasValue ?
                new ObjectParameter("NextReviewDateFrom", nextReviewDateFrom) :
                new ObjectParameter("NextReviewDateFrom", typeof(System.DateTime));
    
            var nextReviewDateToParameter = nextReviewDateTo.HasValue ?
                new ObjectParameter("NextReviewDateTo", nextReviewDateTo) :
                new ObjectParameter("NextReviewDateTo", typeof(System.DateTime));
    
            var effeciencyDateFromParameter = effeciencyDateFrom.HasValue ?
                new ObjectParameter("EffeciencyDateFrom", effeciencyDateFrom) :
                new ObjectParameter("EffeciencyDateFrom", typeof(System.DateTime));
    
            var effeciencyDateToParameter = effeciencyDateTo.HasValue ?
                new ObjectParameter("EffeciencyDateTo", effeciencyDateTo) :
                new ObjectParameter("EffeciencyDateTo", typeof(System.DateTime));
    
            var readTypeParameter = readType != null ?
                new ObjectParameter("ReadType", readType) :
                new ObjectParameter("ReadType", typeof(string));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var reviewNecassaryChangeParameter = reviewNecassaryChange != null ?
                new ObjectParameter("ReviewNecassaryChange", reviewNecassaryChange) :
                new ObjectParameter("ReviewNecassaryChange", typeof(string));
    
            var mainIDParameter = mainID.HasValue ?
                new ObjectParameter("MainID", mainID) :
                new ObjectParameter("MainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDocuments20_Result>("GetDocuments20", forUserIDParameter, documentIDParameter, nameParameter, numberParameter, administratorParameter, orderByParameter, documentTypeIDParameter, pageParameter, itemsPerPageParameter, projectIDParameter, divisionIDParameter, appSystemIDParameter, workplaceIDParameter, nextReviewDateFromParameter, nextReviewDateToParameter, effeciencyDateFromParameter, effeciencyDateToParameter, readTypeParameter, stateIDParameter, revisionParameter, reviewNecassaryChangeParameter, mainIDParameter);
        }
    }
}
