//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCPack.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadConfirmation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadConfirmation()
        {
            this.ConfirmUserFunctions = new HashSet<ConfirmUserFunction>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public int DocumentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmUserFunction> ConfirmUserFunctions { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
